name: Hangup Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: node detox/demo.js
