name: Hangup Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Bootstrap Lerna
        run: npx lerna@3 bootstrap --no-ci
        env:
          DETOX_DISABLE_POD_INSTALL: true
          DETOX_DISABLE_POSTINSTALL: true
      - run: exec node detox/demo.js
